Improve the docker cleanup script to include volumes
Added image, build, system cleanup

Changed the script to log to the console

Resolved identations issue

updated the container filter

Added filter labels

Added correct labels for the volumes
Add option to remove volumes as part of the system prume command

Add option to remove volumes using the system prume --volume command

Update the script help

Changed the filter to use label=com.gitlab.gitlab-runner.type=cache

> Added -a as part of the available options
> Resolved a bug when selecting options

Ensure correct docker version is installed before launching the commands

Update the correct API version

Images are currently not labeled so will be missed by the docker prune / system command. Removing the label for these 2 commands till the same is implemented.

Apply 1 suggestion(s) to 1 file(s)

Apply 1 suggestion(s) to 1 file(s)

Apply 1 suggestion(s) to 1 file(s)

Apply 1 suggestion(s) to 1 file(s)

Apply 1 suggestion(s) to 1 file(s)

Apply 1 suggestion(s) to 1 file(s)

Apply 1 suggestion(s) to 1 file(s)

Apply 1 suggestion(s) to 1 file(s)

Update script to only remove containers and volumes

diff --git a/packaging/root/usr/share/gitlab-runner/clear-docker-cache b/packaging/root/usr/share/gitlab-runner/clear-docker-cache
--- a/packaging/root/usr/share/gitlab-runner/clear-docker-cache
+++ b/packaging/root/usr/share/gitlab-runner/clear-docker-cache
@@ -1,15 +1,66 @@
 #!/bin/sh
 
-set -e
-docker version >/dev/null 2>/dev/null
+#########################################################################################
+#  SCRIPT: clear-docker-cache.sh
+#  Description: Used to cleanup old docker containers and volumes
+######################################################################################
+IFS=$'\n\t'
+set -euo pipefail
 
-echo Clearing docker cache...
 
-CONTAINERS=$(docker ps -a -q \
-             --filter=status=exited \
-             --filter=status=dead \
-             --filter=label=com.gitlab.gitlab-runner.type=cache)
+DOCKER_VERSION=$(docker version --format '{{.Server.Version}}') #get docker version
+REQUIRED_DOCKER_VERSION=1.13
 
-if [ -n "${CONTAINERS}" ]; then
-    docker rm -v ${CONTAINERS}
+#print usage information
+usage() {
+   echo "\nUsage: $0 prune|space|help\n"
+   echo  "\tdefault (*)      Remove all unused containers (both dangling and unreferenced) and volumes"
+   echo  "\tprune            Remove all unused containers (both dangling and unreferenced)"
+   echo  "\tspace            Show docker disk usage"
+   echo  "\thelp             Show usage"
+   exit 1 # Exit script after printing usage
+}
+
+if  awk 'BEGIN {exit !('$DOCKER_VERSION' < '$REQUIRED_DOCKER_VERSION')}'; then
+    echo "\nERROR: Your current API version is lower than 1.25. The client and daemon API must both be at least 1.25+ to run these commands. Kindly upgrade your docker version\n"
+    exit 1
 fi
+
+
+COMMAND="${1:-new}"
+
+case "$COMMAND" in
+
+  prune)
+
+    echo  "\nCheck and remove all unused containers (both dangling and unreferenced)"
+    echo  "-----------------------------------------------------------------------\n\n"
+    docker system prune -af --filter label=com.gitlab.gitlab-runner.managed=true
+    
+    exit 0
+    ;;
+
+  space)
+
+    echo  "\nShow docker disk usage"
+    echo  "----------------------\n"
+    docker system df   
+    
+    exit 0
+    ;;
+
+  help)
+
+    usage
+    ;;
+
+  *)  
+
+    echo  "\nCheck and remove all unused containers (both dangling and unreferenced) including volumes."
+    echo  "------------------------------------------------------------------------------------------\n\n"
+    docker system prune --volumes -af --filter label=com.gitlab.gitlab-runner.managed=true
+
+    exit 0
+    ;;
+
+esac
