Switch to markdownlint-cli2

diff --git a/scripts/lint-docs b/scripts/lint-docs
--- a/scripts/lint-docs
+++ b/scripts/lint-docs
@@ -18,10 +18,10 @@ else
 fi
 
 echo "Lint Markdown"
-if command -v markdownlint >/dev/null 2>&1; then
-    markdownlint --config "${GIT_ROOT}/.markdownlint.yml" 'docs/**/*.md' || ((ERROR_RESULTS++))
+if command -v markdownlint-cli2-config >/dev/null 2>&1; then
+    markdownlint-cli2-config "${GIT_ROOT}/.markdownlint.yml" 'docs/**/*.md' || ((ERROR_RESULTS++))
 else
-    echo "markdownlint is missing, please install it from https://github.com/igorshubovych/markdownlint-cli#installation"
+    echo "markdownlint-2 is missing, please install it from https://github.com/DavidAnson/markdownlint-cli2#install"
 fi
 
 if [ "${ERROR_RESULTS}" -ne 0 ]; then
